### ISSUE TITLE
默认加密方式是什么，没有看到有选择加密方式的框

### ISSUE THREAD

**Issue by spritecn** [shadowsocks-plus/Shadowsocks-Plus-Win#2]

**Comment by jm33-m0** [comment]
`aes-256-cfb`

> 我感觉设成别的没有意义，所以就没给选择别的加密方式

**Comment by spritecn** [comment]
有没有尝试过 ssp以服务方式运行 ，我新建服务后无法启动 ，提示服务没有及时响应启动或控制请求，是程序本身不支持，还是我建的服务有问题

**Comment by jm33-m0** [comment]
不需要以服务运行，你试图把一个没有注册服务的程序作为服务使用，当然会缺少启动和停止方式，事实上，我已经加入了开机自动启动的选项，你勾选之后就可以不用每次都打开这个客户端了，代理会随机启动
